version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master
      POSTGRES_DB: sb_students_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: